// Runtime environment configuration
// This file is auto-generated by Docker at runtime
// For local development, this empty file prevents 404 errors
// The app will use build-time config from src/config.ts

window.ENV_CONFIG = {
    // API_URL: 'http://localhost:3000/api',
    // WS_URL: 'ws://localhost:3000/ws'
};
